### ISSUE TITLE
Nice job!

### ISSUE THREAD

**Issue by ReiMasa** [Mitsukiii/Simple-PokeOne-Bot#1]
Really glad I found this by searching it on github. Is there anyway we could keep up to date on Discord, or suggest features? Or somewhere to keesp up with things like this for pokeone?

Suggestion that is probably already an obvious suggestion: Being able to hunt/catch specified pokemon in an area (i.e scythers)

**Comment by Mitsukiii** [comment]
I don't want to make a Discord Server for such a small Project and i can't work much rn on the Bot due the Server Issues the Game currently have.

But u can message me on Discord: a Serious Guy#1337
