### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Namenlos0x9** [Mitsukiii/Simple-PokeOne-Bot#3]
https://www.virustotal.com/#/file/40f6de71d93b910d613d0c1f3c2f0d518bd1d9a39d13f2a7ecc58e77064fa736/detection

Anything to say?

**Comment by Mitsukiii** [comment]
Download AutoIT, SCiTe and the Source Code and compile it yourself.

Open the .au3 Source Code and press F5 to Run the Script.


Most Autoit Scripts will be false flagged as Virus, so no need to worry.
